_wandb:
    value:
        cli_version: 0.22.2
        e:
            5zg6uj3p8bpf0l76qmxp3595xis11vw4:
                args:
                    - config/device_experiments.yml
                    - --device
                    - odin
                    - --experiment
                    - odin_pop_300_gen_100_mut_020
                    - --run
                    - "1"
                    - --constraint
                    - "2.1"
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                email: achalypatel3403@gmail.com
                executable: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/venv/bin/python3
                git:
                    commit: a658196545e4d2b545238bb2571433280c71bb5d
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning
                host: ODIN-IEEE
                os: Linux-6.8.0-83-generic-x86_64-with-glibc2.39
                program: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.12.3
                root: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-13T13:30:47.644197Z"
                writerId: 5zg6uj3p8bpf0l76qmxp3595xis11vw4
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 2
                - 13
                - 15
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
