_wandb:
    value:
        cli_version: 0.22.2
        e:
            xbc7g2n7q5jsnzb3ckoqjxdraoxmz20u:
                args:
                    - config/device_experiments.yml
                    - --device
                    - nyquist
                    - --constraint
                    - "2.2"
                    - --experiment
                    - nyquist_adaptive_search
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "232969940992"
                        used: "117517664256"
                email: achalypatel3403@gmail.com
                executable: /home/orenda/miniconda3/bin/python3
                git:
                    commit: d073caa645af96744b6d86302ea7129980966e64
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning.git
                host: nyquist
                memory:
                    total: "33573376000"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.13.2
                root: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-13T04:55:01.164043Z"
                writerId: xbc7g2n7q5jsnzb3ckoqjxdraoxmz20u
        m: []
        python_version: 3.13.2
        t:
            "3":
                - 13
                - 15
                - 16
            "4": 3.13.2
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
algorithm:
    value: evolutionary_algorithm
assignment:
    value: COEN432_Assignment1
crossover_rate:
    value: 0.85
device:
    value: nyquist
device_workers:
    value: 8
experiment_name:
    value: nyquist_adaptive_search
generations:
    value: 150
max_workers:
    value: 8
mutation_rate:
    value: 0.015
population_size:
    value: 200
problem_2.2_crossover_rate:
    value: 0.85
problem_2.2_generations:
    value: 150
problem_2.2_mutation_rate:
    value: 0.015
problem_2.2_population_size:
    value: 200
problem_2.2_sequence_constraint:
    value: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
problem_2.2_sequence_length:
    value: 218
problem_2.2_structure_constraint:
    value: '...................((((((((..((((((.((((((......((((((((..........))))))))..)))))).))))))))))))))........((((((([[[((......]]]..))...)))))))((((((.[[[.))))))....((((((((.....((((((((....))))))))......))))))))...]]].....'
problem_2.2_tournament_size:
    value: 3
problem_type:
    value: inverse_rna_folding
problems:
    value:
        - "2.2"
problems_count:
    value: 1
run_number:
    value: 1
tournament_size:
    value: 3
