_wandb:
    value:
        cli_version: 0.22.2
        e:
            hg5iizm3ebedt46ikr4h3k1xyn6jq5o0:
                args:
                    - config/device_experiments.yml
                    - --device
                    - nyquist
                    - --constraint
                    - "2.1"
                    - --experiment
                    - nyquist_pop_250_gen_120_mut_010
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "232969940992"
                        used: "119486377984"
                email: achalypatel3403@gmail.com
                executable: /home/orenda/miniconda3/bin/python3
                git:
                    commit: a658196545e4d2b545238bb2571433280c71bb5d
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning.git
                host: nyquist
                memory:
                    total: "33573376000"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.13.2
                root: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-13T12:50:21.748130Z"
                writerId: hg5iizm3ebedt46ikr4h3k1xyn6jq5o0
        m: []
        python_version: 3.13.2
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.13.2
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
crossover_rate:
    value: 0.8
device:
    value: nyquist
early_termination_fitness:
    value: 0.95
elite_percentage:
    value: 0.8
experiment_name:
    value: nyquist_pop_250_gen_120_mut_010
generations:
    value: 120
high_fitness_streak_threshold:
    value: 25
mutation_rate:
    value: 0.01
population_size:
    value: 200
problem_id:
    value: "2.1"
run_number:
    value: 1
sequence_length:
    value: 218
structure_length:
    value: 219
timestamp:
    value: "20251013_085021"
tournament_size:
    value: 4
