_wandb:
    value:
        cli_version: 0.22.2
        e:
            av7fezcxc277ubqmhflnr3fe00jtfh2f:
                args:
                    - config/device_experiments.yml
                    - --device
                    - nyquist
                    - --experiment
                    - nyquist_pop_500_gen_500_mut_015
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "232969940992"
                        used: "121867845632"
                email: achalypatel3403@gmail.com
                executable: /home/orenda/miniconda3/bin/python3
                git:
                    commit: f905bc1aacc256e5fb2d197afd159d21c9ca9440
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning.git
                host: nyquist
                memory:
                    total: "33573376000"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.13.2
                root: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-13T17:07:22.975302Z"
                writerId: av7fezcxc277ubqmhflnr3fe00jtfh2f
        m: []
        python_version: 3.13.2
        t:
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.13.2
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
crossover_rate:
    value: 0.85
device:
    value: nyquist
early_termination_fitness:
    value: 0.95
elite_percentage:
    value: 0.1
experiment_name:
    value: nyquist_pop_500_gen_500_mut_015
generations:
    value: 500
high_fitness_streak_threshold:
    value: 25
mutation_rate:
    value: 0.015
population_size:
    value: 500
problem_id:
    value: "1.2"
run_number:
    value: 1
sequence_length:
    value: 78
structure_length:
    value: 78
timestamp:
    value: "20251013_130722"
tournament_size:
    value: 3
