_wandb:
    value:
        cli_version: 0.22.2
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
crossover_rate:
    value: 0.8
device:
    value: odin
experiment_name:
    value: odin_intensive_optimization
generations:
    value: 150
max_workers:
    value: 28
mutation_rate:
    value: 0.008
population_size:
    value: 500
problems:
    value:
        - "1.2"
run_number:
    value: 1
tournament_size:
    value: 5
