_wandb:
    value:
        cli_version: 0.22.2
        e:
            pna023dbxghjtl4vfu99buwobj2mui6c:
                args:
                    - config/device_experiments.yml
                    - --device
                    - nyquist
                    - --experiment
                    - nyquist_pop_200_gen_150_mut_015
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "232969940992"
                        used: "126139883520"
                email: achalypatel3403@gmail.com
                executable: /home/orenda/miniconda3/bin/python3
                git:
                    commit: ab8ea25a1ced16f5a9a09e59eb7f53012444f726
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning.git
                host: nyquist
                memory:
                    total: "33573376000"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.13.2
                root: /home/orenda/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-14T08:37:36.151777Z"
                writerId: pna023dbxghjtl4vfu99buwobj2mui6c
        m:
            - "1": fitness_avg
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": global_step
              "6":
                - 3
              "7":
                - 5
            - "1": diversity
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": generation
              "6":
                - 3
              "7":
                - 5
            - "1": fitness_max
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.13.2
        t:
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 62
                - 63
            "4": 3.13.2
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
crossover_rate:
    value: 0.85
device:
    value: nyquist
device_workers:
    value: 10
experiment_name:
    value: nyquist_pop_200_gen_150_mut_015
generations:
    value: 150
mutation_rate:
    value: 0.015
population_size:
    value: 200
problems:
    value:
        - "1.1"
        - "1.2"
        - "2.1"
        - "2.2"
        - "3.1"
        - "3.2"
run_number:
    value: 1
tournament_size:
    value: 3
