_wandb:
    value:
        cli_version: 0.22.2
        e:
            1txess5jjh84gk64ff7vuapo00saki63:
                args:
                    - config/device_experiments.yml
                    - --device
                    - odin
                    - --experiment
                    - odin_intensive_optimization
                    - --constraint
                    - "1.1"
                    - --run
                    - "1"
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "473624838144"
                        used: "60448313344"
                email: achalypatel3403@gmail.com
                executable: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/venv/bin/python3
                git:
                    commit: d073caa645af96744b6d86302ea7129980966e64
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning
                gpu: NVIDIA GeForce RTX 5070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 6144
                      memoryTotal: "12820938752"
                      name: NVIDIA GeForce RTX 5070
                      uuid: GPU-7501b1c9-9eb0-ee9a-fbf7-3b85c97ec088
                host: ODIN-IEEE
                memory:
                    total: "98714808320"
                os: Linux-6.8.0-83-generic-x86_64-with-glibc2.39
                program: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.12.3
                root: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-13T05:07:57.492475Z"
                writerId: 1txess5jjh84gk64ff7vuapo00saki63
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
algorithm:
    value: evolutionary_algorithm
assignment:
    value: COEN432_Assignment1
crossover_rate:
    value: 0.8
device:
    value: odin
device_workers:
    value: 28
experiment_name:
    value: odin_intensive_optimization
generations:
    value: 150
max_workers:
    value: 28
mutation_rate:
    value: 0.008
population_size:
    value: 100
problem_1.1_crossover_rate:
    value: 0.8
problem_1.1_generations:
    value: 150
problem_1.1_mutation_rate:
    value: 0.008
problem_1.1_population_size:
    value: 100
problem_1.1_sequence_constraint:
    value: GARMUWYMNKKSSGMUCCKCYAGCNCMMNGAGKNCWAUKSKRUNCGNMYCNMNSCKCNCNCKUKKSWSAACSSSAMCN
problem_1.1_sequence_length:
    value: 78
problem_1.1_structure_constraint:
    value: ((((....))))....(((((.......)))))............(((((.......[[[[[[))))).]]]]]]...
problem_1.1_tournament_size:
    value: 5
problem_type:
    value: inverse_rna_folding
problems:
    value:
        - "1.1"
problems_count:
    value: 1
run_number:
    value: 1
tournament_size:
    value: 5
