_wandb:
    value:
        cli_version: 0.22.2
        e:
            o2km4b44oh1qoo07d3ldwj6aqyh7k65b:
                args:
                    - config/device_experiments.yml
                    - --device
                    - odin
                    - --experiment
                    - odin_pop_300_gen_100_mut_020
                    - --run
                    - "1"
                    - --constraint
                    - "2.1"
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "473624838144"
                        used: "66490372096"
                email: achalypatel3403@gmail.com
                executable: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/venv/bin/python3
                git:
                    commit: a658196545e4d2b545238bb2571433280c71bb5d
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning
                gpu: NVIDIA GeForce RTX 5070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 6144
                      memoryTotal: "12820938752"
                      name: NVIDIA GeForce RTX 5070
                      uuid: GPU-7501b1c9-9eb0-ee9a-fbf7-3b85c97ec088
                host: ODIN-IEEE
                memory:
                    total: "98714808320"
                os: Linux-6.8.0-83-generic-x86_64-with-glibc2.39
                program: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.12.3
                root: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-13T13:16:14.663097Z"
                writerId: o2km4b44oh1qoo07d3ldwj6aqyh7k65b
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
crossover_rate:
    value: 0.8
device:
    value: odin
early_termination_fitness:
    value: 0.95
elite_percentage:
    value: 0.08
experiment_name:
    value: odin_pop_300_gen_100_mut_020
generations:
    value: 100
high_fitness_streak_threshold:
    value: 25
mutation_rate:
    value: 0.02
population_size:
    value: 300
problem_id:
    value: "2.1"
run_number:
    value: 1
sequence_length:
    value: 218
structure_length:
    value: 219
timestamp:
    value: "20251013_091614"
tournament_size:
    value: 3
