_wandb:
    value:
        cli_version: 0.22.2
        e:
            662dzgupt8f0tlyn7lrba18whl24bd0o:
                args:
                    - config/device_experiments.yml
                    - --device
                    - odin
                    - --run
                    - "1"
                    - --constraint
                    - "3.2"
                    - --experiment
                    - odin_pop_300_gen_150_mut_020
                codePath: Assignment_1/src/ea_runner.py
                codePathLocal: src/ea_runner.py
                email: achalypatel3403@gmail.com
                executable: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/venv/bin/python3
                git:
                    commit: 627423e4928c60e875dc8ec03b409d98253bbb71
                    remote: https://github.com/ac-pate/Evolutionary-Algorithms-and-Machine-Learning
                host: ODIN-IEEE
                os: Linux-6.8.0-83-generic-x86_64-with-glibc2.39
                program: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1/src/ea_runner.py
                python: CPython 3.12.3
                root: /home/odin/achal/Evolutionary-Algorithms-and-Machine-Learning/Assignment_1
                startedAt: "2025-10-13T16:40:52.768945Z"
                writerId: 662dzgupt8f0tlyn7lrba18whl24bd0o
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 2
                - 13
                - 15
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
