# RNA Folding EA - Device-Optimized Experiments
# All 6 problems from EA_Assignment_1_constraints - Sheet1.csv
# Problem definitions:
# 1.1: Known sequence with complex structure
# 1.2: Unknown sequence (all N) with same structure as 1.1
# 2.1: Long complex sequence with multiple domains
# 2.2: Unknown sequence (all N) with same structure as 2.1
# 3.1: Medium sequence with pseudoknots
# 3.2: Unknown sequence (all N) with same structure as 3.1

PROBLEMS:
  "1.1":
    STRUCTURE_CONSTRAINT: "((((....))))....(((((.......)))))............(((((.......[[[[[[))))).]]]]]]..."
    SEQUENCE_CONSTRAINT: "GARMUWYMNKKSSGMUCCKCYAGCNCMMNGAGKNCWAUKSKRUNCGNMYCNMNSCKCNCNCKUKKSWSAACSSSAMCN"
  "1.2":
    STRUCTURE_CONSTRAINT: "((((....))))....(((((.......)))))............(((((.......[[[[[[))))).]]]]]]..."
    SEQUENCE_CONSTRAINT: "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
  "2.1":
    STRUCTURE_CONSTRAINT: "...................((((((((..((((((.((((((......((((((((..........))))))))..)))))).))))))))))))))........((((((([[[((......]]]..))...)))))))((((((.[[[.))))))....((((((((.....((((((((....))))))))......))))))))...]]]....."
    SEQUENCE_CONSTRAINT: "UUAWUARWUAMAGSGCSNNUSNANWRUACNNMWAUAGNUAUNNAGUAUYAAAAGUNANRNURGUNNARSYUUUAURGAKAAYGNUUUGGRUNYUGUNGMCRNGGWNNRKAKWGAUCKMAYCAGAUCKRCGNAKGCURUNCSSSAUGYGRCACMUNCGNYRGCUUMUUAWGWARWKCAWURAGGUNACNUMRWGKMCNWRGWUWWUAAGAUCGCNAAAY"
  "2.2":
    STRUCTURE_CONSTRAINT: "...................((((((((..((((((.((((((......((((((((..........))))))))..)))))).))))))))))))))........((((((([[[((......]]]..))...)))))))((((((.[[[.))))))....((((((((.....((((((((....))))))))......))))))))...]]]....."
    SEQUENCE_CONSTRAINT: "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
  "3.1":
    STRUCTURE_CONSTRAINT: "..............[[...((((((((((........(((((..(((.......)))...)))))))))))))))........(((((((...(((....)))]]...)))))))(((((((....)))))))..................((((((((....))))))))........................"
    SEQUENCE_CONSTRAINT: "ARUUSNMUAGWAGCGCCNRMNNURRUUGGGNCRRAAAUNMNKNRNRNNSMANWCSCKSNAANGUMUCSAUYNKUKKACKMGGRNGAGRYYWAUCSAAGUUNNGSCSGRAGNYUYCCKGNYNKKNAUGCANYCKUKAARYNUUAMUYNCRANUYAYYUGGGNNAYCMWGNGGNCWNANNNGWAAUSAARMRUSCYY"
  "3.2":
    STRUCTURE_CONSTRAINT: "..............[[...((((((((((........(((((..(((.......)))...)))))))))))))))........(((((((...(((....)))]]...)))))))(((((((....)))))))..................((((((((....))))))))........................"
    SEQUENCE_CONSTRAINT: "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"

EXPERIMENTS:
  # ODIN - AMD Ryzen 9 9950X (32 threads) - HIGH PERFORMANCE CONFIGURATION
  # Intensive optimization with large populations for complex RNA folding problems
  
  - NAME: odin_pop_1000_gen_200_mut_02
    POPULATION_SIZE: 1000
    GENERATIONS: 200
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.02
    TOURNAMENT_SIZE: 10
    ELITE_PERCENTAGE: 0.01
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: odin_pop_600_gen_200_mut_012
    POPULATION_SIZE: 600
    GENERATIONS: 200
    CROSSOVER_RATE: 0.75
    MUTATION_RATE: 0.012
    TOURNAMENT_SIZE: 8
    ELITE_PERCENTAGE: 0.01
    ELITE_PERCENTAGE: 0.15
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: odin_pop_400_gen_200_mut_012
    POPULATION_SIZE: 400
    GENERATIONS: 200
    CROSSOVER_RATE: 0.75
    MUTATION_RATE: 0.012
    TOURNAMENT_SIZE: 6
    ELITE_PERCENTAGE: 0.1
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25



  - NAME: odin_pop_300_gen_100_mut_020
    POPULATION_SIZE: 300
    GENERATIONS: 100
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.02
    TOURNAMENT_SIZE: 3
    ELITE_PERCENTAGE: 0.08
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: odin_pop_200_gen_150_mut_015
    POPULATION_SIZE: 200
    GENERATIONS: 150
    CROSSOVER_RATE: 0.85
    MUTATION_RATE: 0.015
    TOURNAMENT_SIZE: 6
    ELITE_PERCENTAGE: 0.12
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25


  # NYQUIST - AMD Ryzen 5 3600 (12 threads) - BALANCED PERFORMANCE CONFIGURATION
  # Moderate populations optimized for multi-threaded efficiency
  - NAME: nyquist_pop_300_gen_1000_mut_010
    POPULATION_SIZE: 300
    GENERATIONS: 1000
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.01
    TOURNAMENT_SIZE: 5
    ELITE_PERCENTAGE: 0.18
    EARLY_TERMINATION_FITNESS: 0.95 
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: nyquist_pop_200_gen_150_mut_015
    POPULATION_SIZE: 200
    GENERATIONS: 150
    CROSSOVER_RATE: 0.85
    MUTATION_RATE: 0.015
    TOURNAMENT_SIZE: 3
    ELITE_PERCENTAGE: 0.10
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: nyquist_pop_180_gen_100_mut_018
    POPULATION_SIZE: 180
    GENERATIONS: 100
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.018
    TOURNAMENT_SIZE: 5
    ELITE_PERCENTAGE: 0.15
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  # LAPTOP - HP Spectre Intel i7-1260P (12 threads) - MOBILE OPTIMIZED CONFIGURATION
  # Thermal-aware configurations for sustained mobile performance
  - NAME: laptop_pop_150_gen_100_mut_012
    POPULATION_SIZE: 150
    GENERATIONS: 100
    CROSSOVER_RATE: 0.75
    MUTATION_RATE: 0.012
    TOURNAMENT_SIZE: 3
    ELITE_PERCENTAGE: 0.10
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: laptop_pop_120_gen_130_mut_018
    POPULATION_SIZE: 120
    GENERATIONS: 130
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.018
    TOURNAMENT_SIZE: 4
    ELITE_PERCENTAGE: 0.12
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: laptop_pop_100_gen_80_mut_025
    POPULATION_SIZE: 100
    GENERATIONS: 80
    CROSSOVER_RATE: 0.85
    MUTATION_RATE: 0.025
    TOURNAMENT_SIZE: 5
    ELITE_PERCENTAGE: 0.15
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  # MINI-PC - Dell OptiPlex 7050 (estimated 8 threads) - RESOURCE EFFICIENT CONFIGURATION
  # Optimized for limited computational resources with extended runtime
  - NAME: minipc_pop_100_gen_120_mut_015
    POPULATION_SIZE: 100
    GENERATIONS: 120
    CROSSOVER_RATE: 0.7
    MUTATION_RATE: 0.015
    TOURNAMENT_SIZE: 3
    ELITE_PERCENTAGE: 0.10
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: minipc_pop_80_gen_160_mut_020
    POPULATION_SIZE: 80
    GENERATIONS: 160
    CROSSOVER_RATE: 0.75
    MUTATION_RATE: 0.02
    TOURNAMENT_SIZE: 2
    ELITE_PERCENTAGE: 0.12
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25

  - NAME: minipc_pop_60_gen_100_mut_030
    POPULATION_SIZE: 60
    GENERATIONS: 100
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.030
    TOURNAMENT_SIZE: 4
    ELITE_PERCENTAGE: 0.15
    EARLY_TERMINATION_FITNESS: 0.95
    HIGH_FITNESS_STREAK_THRESHOLD: 25