# RNA Folding EA - Device-Optimized Experiments
# All 6 problems from EA_Assignment_1_constraints - Sheet1.csv
# Problem definitions:
# 1.1: Known sequence with complex structure
# 1.2: Unknown sequence (all N) with same structure as 1.1
# 2.1: Long complex sequence with multiple domains
# 2.2: Unknown sequence (all N) with same structure as 2.1
# 3.1: Medium sequence with pseudoknots
# 3.2: Unknown sequence (all N) with same structure as 3.1

PROBLEMS:
  "1.1":
    STRUCTURE_CONSTRAINT: "((((....))))....(((((.......)))))............(((((.......[[[[[[))))).]]]]]]..."
    SEQUENCE_CONSTRAINT: "GARMUWYMNKKSSGMUCCKCYAGCNCMMNGAGKNCWAUKSKRUNCGNMYCNMNSCKCNCNCKUKKSWSAACSSSAMCN"
  "1.2":
    STRUCTURE_CONSTRAINT: "((((....))))....(((((.......)))))............(((((.......[[[[[[))))).]]]]]]..."
    SEQUENCE_CONSTRAINT: "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
  "2.1":
    STRUCTURE_CONSTRAINT: "...................((((((((..((((((.((((((......((((((((..........))))))))..)))))).))))))))))))))........((((((([[[((......]]]..))...)))))))((((((.[[[.))))))....((((((((.....((((((((....))))))))......))))))))...]]]....."
    SEQUENCE_CONSTRAINT: "UUAWUARWUAMAGSGCSNNUSNANWRUACNNMWAUAGNUAUNNAGUAUYAAAAGUNANRNURGUNNARSYUUUAURGAKAAYGNUUUGGRUNYUGUNGMCRNGGWNNRKAKWGAUCKMAYCAGAUCKRCGNAKGCURUNCSSSAUGYGRCACMUNCGNYRGCUUMUUAWGWARWKCAWURAGGUNACNUMRWGKMCNWRGWUWWUAAGAUCGCNAAAY"
  "2.2":
    STRUCTURE_CONSTRAINT: "...................((((((((..((((((.((((((......((((((((..........))))))))..)))))).))))))))))))))........((((((([[[((......]]]..))...)))))))((((((.[[[.))))))....((((((((.....((((((((....))))))))......))))))))...]]]....."
    SEQUENCE_CONSTRAINT: "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
  "3.1":
    STRUCTURE_CONSTRAINT: "..............[[...((((((((((........(((((..(((.......)))...)))))))))))))))........(((((((...(((....)))]]...)))))))(((((((....)))))))..................((((((((....))))))))........................"
    SEQUENCE_CONSTRAINT: "ARUUSNMUAGWAGCGCCNRMNNURRUUGGGNCRRAAAUNMNKNRNRNNSMANWCSCKSNAANGUMUCSAUYNKUKKACKMGGRNGAGRYYWAUCSAAGUUNNGSCSGRAGNYUYCCKGNYNKKNAUGCANYCKUKAARYNUUAMUYNCRANUYAYYUGGGNNAYCMWGNGGNCWNANNNGWAAUSAARMRUSCYY"
  "3.2":
    STRUCTURE_CONSTRAINT: "..............[[...((((((((((........(((((..(((.......)))...)))))))))))))))........(((((((...(((....)))]]...)))))))(((((((....)))))))..................((((((((....))))))))........................"
    SEQUENCE_CONSTRAINT: "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"

EXPERIMENTS:
  # ODIN - AMD Ryzen 9 9950X (32 threads) - HIGH PERFORMANCE CONFIGURATION
  # Intensive optimization with large populations for complex RNA folding problems
  - NAME: odin_intensive_optimization
    POPULATION_SIZE: 500
    GENERATIONS: 150
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.008
    TOURNAMENT_SIZE: 5

  - NAME: odin_extended_search
    POPULATION_SIZE: 400
    GENERATIONS: 200
    CROSSOVER_RATE: 0.75
    MUTATION_RATE: 0.012
    TOURNAMENT_SIZE: 4

  # NYQUIST - AMD Ryzen 5 3600 (12 threads) - BALANCED PERFORMANCE CONFIGURATION
  # Moderate populations optimized for multi-threaded efficiency
  - NAME: nyquist_standard_protocol
    POPULATION_SIZE: 250
    GENERATIONS: 120
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.01
    TOURNAMENT_SIZE: 4

  - NAME: nyquist_adaptive_search
    POPULATION_SIZE: 200
    GENERATIONS: 150
    CROSSOVER_RATE: 0.85
    MUTATION_RATE: 0.015
    TOURNAMENT_SIZE: 3

  # LAPTOP - HP Spectre Intel i7-1260P (12 threads) - MOBILE OPTIMIZED CONFIGURATION
  # Thermal-aware configurations for sustained mobile performance
  - NAME: laptop_mobile_optimization
    POPULATION_SIZE: 150
    GENERATIONS: 100
    CROSSOVER_RATE: 0.75
    MUTATION_RATE: 0.012
    TOURNAMENT_SIZE: 3

  - NAME: laptop_precision_search
    POPULATION_SIZE: 120
    GENERATIONS: 130
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.018
    TOURNAMENT_SIZE: 4

  # MINI-PC - Dell OptiPlex 7050 (estimated 8 threads) - RESOURCE EFFICIENT CONFIGURATION
  # Optimized for limited computational resources with extended runtime
  - NAME: minipc_steady_state
    POPULATION_SIZE: 100
    GENERATIONS: 120
    CROSSOVER_RATE: 0.7
    MUTATION_RATE: 0.015
    TOURNAMENT_SIZE: 3

  - NAME: minipc_long_term_evolution
    POPULATION_SIZE: 80
    GENERATIONS: 160
    CROSSOVER_RATE: 0.75
    MUTATION_RATE: 0.02
    TOURNAMENT_SIZE: 2