PROBLEMS:
  "test":
    STRUCTURE_CONSTRAINT: "((..))"
    SEQUENCE_CONSTRAINT: "NNNNNN"

EXPERIMENTS:
  - NAME: test_micro_run
    POPULATION_SIZE: 6
    GENERATIONS: 3
    CROSSOVER_RATE: 0.8
    MUTATION_RATE: 0.1
    TOURNAMENT_SIZE: 2
